language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo build --all
stages:
  - Check
  - Clippy
  - Test
jobs:
  include:
    - stage: Check
      name: Format
      script:
        - make fmt
    - stage: Clippy
      name: Clippy
      script:
        - make clippy
    - stage: Test
      name: Unitest
      script:
        - make test
